###################################################################

# Created by write_sdc on Mon Nov  1 01:21:08 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
create_clock [get_ports clock]  -name CLK  -period 5  -waveform {0 2.5}
group_path -name input_group  -from [list [get_ports clock] [get_ports reset] [get_ports                    \
{io_controlSignal_wr[31]}] [get_ports {io_controlSignal_wr[30]}] [get_ports    \
{io_controlSignal_wr[29]}] [get_ports {io_controlSignal_wr[28]}] [get_ports    \
{io_controlSignal_wr[27]}] [get_ports {io_controlSignal_wr[26]}] [get_ports    \
{io_controlSignal_wr[25]}] [get_ports {io_controlSignal_wr[24]}] [get_ports    \
{io_controlSignal_wr[23]}] [get_ports {io_controlSignal_wr[22]}] [get_ports    \
{io_controlSignal_wr[21]}] [get_ports {io_controlSignal_wr[20]}] [get_ports    \
{io_controlSignal_wr[19]}] [get_ports {io_controlSignal_wr[18]}] [get_ports    \
{io_controlSignal_wr[17]}] [get_ports {io_controlSignal_wr[16]}] [get_ports    \
{io_controlSignal_wr[15]}] [get_ports {io_controlSignal_wr[14]}] [get_ports    \
{io_controlSignal_wr[13]}] [get_ports {io_controlSignal_wr[12]}] [get_ports    \
{io_controlSignal_wr[11]}] [get_ports {io_controlSignal_wr[10]}] [get_ports    \
{io_controlSignal_wr[9]}] [get_ports {io_controlSignal_wr[8]}] [get_ports      \
{io_controlSignal_wr[7]}] [get_ports {io_controlSignal_wr[6]}] [get_ports      \
{io_controlSignal_wr[5]}] [get_ports {io_controlSignal_wr[4]}] [get_ports      \
{io_controlSignal_wr[3]}] [get_ports {io_controlSignal_wr[2]}] [get_ports      \
{io_controlSignal_wr[1]}] [get_ports {io_controlSignal_wr[0]}] [get_ports      \
io_controlSignal_wr_en] [get_ports io_run] [get_ports {io_north_in_a[63]}]     \
[get_ports {io_north_in_a[62]}] [get_ports {io_north_in_a[61]}] [get_ports     \
{io_north_in_a[60]}] [get_ports {io_north_in_a[59]}] [get_ports                \
{io_north_in_a[58]}] [get_ports {io_north_in_a[57]}] [get_ports                \
{io_north_in_a[56]}] [get_ports {io_north_in_a[55]}] [get_ports                \
{io_north_in_a[54]}] [get_ports {io_north_in_a[53]}] [get_ports                \
{io_north_in_a[52]}] [get_ports {io_north_in_a[51]}] [get_ports                \
{io_north_in_a[50]}] [get_ports {io_north_in_a[49]}] [get_ports                \
{io_north_in_a[48]}] [get_ports {io_north_in_a[47]}] [get_ports                \
{io_north_in_a[46]}] [get_ports {io_north_in_a[45]}] [get_ports                \
{io_north_in_a[44]}] [get_ports {io_north_in_a[43]}] [get_ports                \
{io_north_in_a[42]}] [get_ports {io_north_in_a[41]}] [get_ports                \
{io_north_in_a[40]}] [get_ports {io_north_in_a[39]}] [get_ports                \
{io_north_in_a[38]}] [get_ports {io_north_in_a[37]}] [get_ports                \
{io_north_in_a[36]}] [get_ports {io_north_in_a[35]}] [get_ports                \
{io_north_in_a[34]}] [get_ports {io_north_in_a[33]}] [get_ports                \
{io_north_in_a[32]}] [get_ports {io_north_in_a[31]}] [get_ports                \
{io_north_in_a[30]}] [get_ports {io_north_in_a[29]}] [get_ports                \
{io_north_in_a[28]}] [get_ports {io_north_in_a[27]}] [get_ports                \
{io_north_in_a[26]}] [get_ports {io_north_in_a[25]}] [get_ports                \
{io_north_in_a[24]}] [get_ports {io_north_in_a[23]}] [get_ports                \
{io_north_in_a[22]}] [get_ports {io_north_in_a[21]}] [get_ports                \
{io_north_in_a[20]}] [get_ports {io_north_in_a[19]}] [get_ports                \
{io_north_in_a[18]}] [get_ports {io_north_in_a[17]}] [get_ports                \
{io_north_in_a[16]}] [get_ports {io_north_in_a[15]}] [get_ports                \
{io_north_in_a[14]}] [get_ports {io_north_in_a[13]}] [get_ports                \
{io_north_in_a[12]}] [get_ports {io_north_in_a[11]}] [get_ports                \
{io_north_in_a[10]}] [get_ports {io_north_in_a[9]}] [get_ports                 \
{io_north_in_a[8]}] [get_ports {io_north_in_a[7]}] [get_ports                  \
{io_north_in_a[6]}] [get_ports {io_north_in_a[5]}] [get_ports                  \
{io_north_in_a[4]}] [get_ports {io_north_in_a[3]}] [get_ports                  \
{io_north_in_a[2]}] [get_ports {io_north_in_a[1]}] [get_ports                  \
{io_north_in_a[0]}] [get_ports {io_north_in_b[63]}] [get_ports                 \
{io_north_in_b[62]}] [get_ports {io_north_in_b[61]}] [get_ports                \
{io_north_in_b[60]}] [get_ports {io_north_in_b[59]}] [get_ports                \
{io_north_in_b[58]}] [get_ports {io_north_in_b[57]}] [get_ports                \
{io_north_in_b[56]}] [get_ports {io_north_in_b[55]}] [get_ports                \
{io_north_in_b[54]}] [get_ports {io_north_in_b[53]}] [get_ports                \
{io_north_in_b[52]}] [get_ports {io_north_in_b[51]}] [get_ports                \
{io_north_in_b[50]}] [get_ports {io_north_in_b[49]}] [get_ports                \
{io_north_in_b[48]}] [get_ports {io_north_in_b[47]}] [get_ports                \
{io_north_in_b[46]}] [get_ports {io_north_in_b[45]}] [get_ports                \
{io_north_in_b[44]}] [get_ports {io_north_in_b[43]}] [get_ports                \
{io_north_in_b[42]}] [get_ports {io_north_in_b[41]}] [get_ports                \
{io_north_in_b[40]}] [get_ports {io_north_in_b[39]}] [get_ports                \
{io_north_in_b[38]}] [get_ports {io_north_in_b[37]}] [get_ports                \
{io_north_in_b[36]}] [get_ports {io_north_in_b[35]}] [get_ports                \
{io_north_in_b[34]}] [get_ports {io_north_in_b[33]}] [get_ports                \
{io_north_in_b[32]}] [get_ports {io_north_in_b[31]}] [get_ports                \
{io_north_in_b[30]}] [get_ports {io_north_in_b[29]}] [get_ports                \
{io_north_in_b[28]}] [get_ports {io_north_in_b[27]}] [get_ports                \
{io_north_in_b[26]}] [get_ports {io_north_in_b[25]}] [get_ports                \
{io_north_in_b[24]}] [get_ports {io_north_in_b[23]}] [get_ports                \
{io_north_in_b[22]}] [get_ports {io_north_in_b[21]}] [get_ports                \
{io_north_in_b[20]}] [get_ports {io_north_in_b[19]}] [get_ports                \
{io_north_in_b[18]}] [get_ports {io_north_in_b[17]}] [get_ports                \
{io_north_in_b[16]}] [get_ports {io_north_in_b[15]}] [get_ports                \
{io_north_in_b[14]}] [get_ports {io_north_in_b[13]}] [get_ports                \
{io_north_in_b[12]}] [get_ports {io_north_in_b[11]}] [get_ports                \
{io_north_in_b[10]}] [get_ports {io_north_in_b[9]}] [get_ports                 \
{io_north_in_b[8]}] [get_ports {io_north_in_b[7]}] [get_ports                  \
{io_north_in_b[6]}] [get_ports {io_north_in_b[5]}] [get_ports                  \
{io_north_in_b[4]}] [get_ports {io_north_in_b[3]}] [get_ports                  \
{io_north_in_b[2]}] [get_ports {io_north_in_b[1]}] [get_ports                  \
{io_north_in_b[0]}] [get_ports {io_east_in_a[63]}] [get_ports                  \
{io_east_in_a[62]}] [get_ports {io_east_in_a[61]}] [get_ports                  \
{io_east_in_a[60]}] [get_ports {io_east_in_a[59]}] [get_ports                  \
{io_east_in_a[58]}] [get_ports {io_east_in_a[57]}] [get_ports                  \
{io_east_in_a[56]}] [get_ports {io_east_in_a[55]}] [get_ports                  \
{io_east_in_a[54]}] [get_ports {io_east_in_a[53]}] [get_ports                  \
{io_east_in_a[52]}] [get_ports {io_east_in_a[51]}] [get_ports                  \
{io_east_in_a[50]}] [get_ports {io_east_in_a[49]}] [get_ports                  \
{io_east_in_a[48]}] [get_ports {io_east_in_a[47]}] [get_ports                  \
{io_east_in_a[46]}] [get_ports {io_east_in_a[45]}] [get_ports                  \
{io_east_in_a[44]}] [get_ports {io_east_in_a[43]}] [get_ports                  \
{io_east_in_a[42]}] [get_ports {io_east_in_a[41]}] [get_ports                  \
{io_east_in_a[40]}] [get_ports {io_east_in_a[39]}] [get_ports                  \
{io_east_in_a[38]}] [get_ports {io_east_in_a[37]}] [get_ports                  \
{io_east_in_a[36]}] [get_ports {io_east_in_a[35]}] [get_ports                  \
{io_east_in_a[34]}] [get_ports {io_east_in_a[33]}] [get_ports                  \
{io_east_in_a[32]}] [get_ports {io_east_in_a[31]}] [get_ports                  \
{io_east_in_a[30]}] [get_ports {io_east_in_a[29]}] [get_ports                  \
{io_east_in_a[28]}] [get_ports {io_east_in_a[27]}] [get_ports                  \
{io_east_in_a[26]}] [get_ports {io_east_in_a[25]}] [get_ports                  \
{io_east_in_a[24]}] [get_ports {io_east_in_a[23]}] [get_ports                  \
{io_east_in_a[22]}] [get_ports {io_east_in_a[21]}] [get_ports                  \
{io_east_in_a[20]}] [get_ports {io_east_in_a[19]}] [get_ports                  \
{io_east_in_a[18]}] [get_ports {io_east_in_a[17]}] [get_ports                  \
{io_east_in_a[16]}] [get_ports {io_east_in_a[15]}] [get_ports                  \
{io_east_in_a[14]}] [get_ports {io_east_in_a[13]}] [get_ports                  \
{io_east_in_a[12]}] [get_ports {io_east_in_a[11]}] [get_ports                  \
{io_east_in_a[10]}] [get_ports {io_east_in_a[9]}] [get_ports                   \
{io_east_in_a[8]}] [get_ports {io_east_in_a[7]}] [get_ports {io_east_in_a[6]}] \
[get_ports {io_east_in_a[5]}] [get_ports {io_east_in_a[4]}] [get_ports         \
{io_east_in_a[3]}] [get_ports {io_east_in_a[2]}] [get_ports {io_east_in_a[1]}] \
[get_ports {io_east_in_a[0]}] [get_ports {io_east_in_b[63]}] [get_ports        \
{io_east_in_b[62]}] [get_ports {io_east_in_b[61]}] [get_ports                  \
{io_east_in_b[60]}] [get_ports {io_east_in_b[59]}] [get_ports                  \
{io_east_in_b[58]}] [get_ports {io_east_in_b[57]}] [get_ports                  \
{io_east_in_b[56]}] [get_ports {io_east_in_b[55]}] [get_ports                  \
{io_east_in_b[54]}] [get_ports {io_east_in_b[53]}] [get_ports                  \
{io_east_in_b[52]}] [get_ports {io_east_in_b[51]}] [get_ports                  \
{io_east_in_b[50]}] [get_ports {io_east_in_b[49]}] [get_ports                  \
{io_east_in_b[48]}] [get_ports {io_east_in_b[47]}] [get_ports                  \
{io_east_in_b[46]}] [get_ports {io_east_in_b[45]}] [get_ports                  \
{io_east_in_b[44]}] [get_ports {io_east_in_b[43]}] [get_ports                  \
{io_east_in_b[42]}] [get_ports {io_east_in_b[41]}] [get_ports                  \
{io_east_in_b[40]}] [get_ports {io_east_in_b[39]}] [get_ports                  \
{io_east_in_b[38]}] [get_ports {io_east_in_b[37]}] [get_ports                  \
{io_east_in_b[36]}] [get_ports {io_east_in_b[35]}] [get_ports                  \
{io_east_in_b[34]}] [get_ports {io_east_in_b[33]}] [get_ports                  \
{io_east_in_b[32]}] [get_ports {io_east_in_b[31]}] [get_ports                  \
{io_east_in_b[30]}] [get_ports {io_east_in_b[29]}] [get_ports                  \
{io_east_in_b[28]}] [get_ports {io_east_in_b[27]}] [get_ports                  \
{io_east_in_b[26]}] [get_ports {io_east_in_b[25]}] [get_ports                  \
{io_east_in_b[24]}] [get_ports {io_east_in_b[23]}] [get_ports                  \
{io_east_in_b[22]}] [get_ports {io_east_in_b[21]}] [get_ports                  \
{io_east_in_b[20]}] [get_ports {io_east_in_b[19]}] [get_ports                  \
{io_east_in_b[18]}] [get_ports {io_east_in_b[17]}] [get_ports                  \
{io_east_in_b[16]}] [get_ports {io_east_in_b[15]}] [get_ports                  \
{io_east_in_b[14]}] [get_ports {io_east_in_b[13]}] [get_ports                  \
{io_east_in_b[12]}] [get_ports {io_east_in_b[11]}] [get_ports                  \
{io_east_in_b[10]}] [get_ports {io_east_in_b[9]}] [get_ports                   \
{io_east_in_b[8]}] [get_ports {io_east_in_b[7]}] [get_ports {io_east_in_b[6]}] \
[get_ports {io_east_in_b[5]}] [get_ports {io_east_in_b[4]}] [get_ports         \
{io_east_in_b[3]}] [get_ports {io_east_in_b[2]}] [get_ports {io_east_in_b[1]}] \
[get_ports {io_east_in_b[0]}] [get_ports {io_west_in_a[63]}] [get_ports        \
{io_west_in_a[62]}] [get_ports {io_west_in_a[61]}] [get_ports                  \
{io_west_in_a[60]}] [get_ports {io_west_in_a[59]}] [get_ports                  \
{io_west_in_a[58]}] [get_ports {io_west_in_a[57]}] [get_ports                  \
{io_west_in_a[56]}] [get_ports {io_west_in_a[55]}] [get_ports                  \
{io_west_in_a[54]}] [get_ports {io_west_in_a[53]}] [get_ports                  \
{io_west_in_a[52]}] [get_ports {io_west_in_a[51]}] [get_ports                  \
{io_west_in_a[50]}] [get_ports {io_west_in_a[49]}] [get_ports                  \
{io_west_in_a[48]}] [get_ports {io_west_in_a[47]}] [get_ports                  \
{io_west_in_a[46]}] [get_ports {io_west_in_a[45]}] [get_ports                  \
{io_west_in_a[44]}] [get_ports {io_west_in_a[43]}] [get_ports                  \
{io_west_in_a[42]}] [get_ports {io_west_in_a[41]}] [get_ports                  \
{io_west_in_a[40]}] [get_ports {io_west_in_a[39]}] [get_ports                  \
{io_west_in_a[38]}] [get_ports {io_west_in_a[37]}] [get_ports                  \
{io_west_in_a[36]}] [get_ports {io_west_in_a[35]}] [get_ports                  \
{io_west_in_a[34]}] [get_ports {io_west_in_a[33]}] [get_ports                  \
{io_west_in_a[32]}] [get_ports {io_west_in_a[31]}] [get_ports                  \
{io_west_in_a[30]}] [get_ports {io_west_in_a[29]}] [get_ports                  \
{io_west_in_a[28]}] [get_ports {io_west_in_a[27]}] [get_ports                  \
{io_west_in_a[26]}] [get_ports {io_west_in_a[25]}] [get_ports                  \
{io_west_in_a[24]}] [get_ports {io_west_in_a[23]}] [get_ports                  \
{io_west_in_a[22]}] [get_ports {io_west_in_a[21]}] [get_ports                  \
{io_west_in_a[20]}] [get_ports {io_west_in_a[19]}] [get_ports                  \
{io_west_in_a[18]}] [get_ports {io_west_in_a[17]}] [get_ports                  \
{io_west_in_a[16]}] [get_ports {io_west_in_a[15]}] [get_ports                  \
{io_west_in_a[14]}] [get_ports {io_west_in_a[13]}] [get_ports                  \
{io_west_in_a[12]}] [get_ports {io_west_in_a[11]}] [get_ports                  \
{io_west_in_a[10]}] [get_ports {io_west_in_a[9]}] [get_ports                   \
{io_west_in_a[8]}] [get_ports {io_west_in_a[7]}] [get_ports {io_west_in_a[6]}] \
[get_ports {io_west_in_a[5]}] [get_ports {io_west_in_a[4]}] [get_ports         \
{io_west_in_a[3]}] [get_ports {io_west_in_a[2]}] [get_ports {io_west_in_a[1]}] \
[get_ports {io_west_in_a[0]}] [get_ports {io_west_in_b[63]}] [get_ports        \
{io_west_in_b[62]}] [get_ports {io_west_in_b[61]}] [get_ports                  \
{io_west_in_b[60]}] [get_ports {io_west_in_b[59]}] [get_ports                  \
{io_west_in_b[58]}] [get_ports {io_west_in_b[57]}] [get_ports                  \
{io_west_in_b[56]}] [get_ports {io_west_in_b[55]}] [get_ports                  \
{io_west_in_b[54]}] [get_ports {io_west_in_b[53]}] [get_ports                  \
{io_west_in_b[52]}] [get_ports {io_west_in_b[51]}] [get_ports                  \
{io_west_in_b[50]}] [get_ports {io_west_in_b[49]}] [get_ports                  \
{io_west_in_b[48]}] [get_ports {io_west_in_b[47]}] [get_ports                  \
{io_west_in_b[46]}] [get_ports {io_west_in_b[45]}] [get_ports                  \
{io_west_in_b[44]}] [get_ports {io_west_in_b[43]}] [get_ports                  \
{io_west_in_b[42]}] [get_ports {io_west_in_b[41]}] [get_ports                  \
{io_west_in_b[40]}] [get_ports {io_west_in_b[39]}] [get_ports                  \
{io_west_in_b[38]}] [get_ports {io_west_in_b[37]}] [get_ports                  \
{io_west_in_b[36]}] [get_ports {io_west_in_b[35]}] [get_ports                  \
{io_west_in_b[34]}] [get_ports {io_west_in_b[33]}] [get_ports                  \
{io_west_in_b[32]}] [get_ports {io_west_in_b[31]}] [get_ports                  \
{io_west_in_b[30]}] [get_ports {io_west_in_b[29]}] [get_ports                  \
{io_west_in_b[28]}] [get_ports {io_west_in_b[27]}] [get_ports                  \
{io_west_in_b[26]}] [get_ports {io_west_in_b[25]}] [get_ports                  \
{io_west_in_b[24]}] [get_ports {io_west_in_b[23]}] [get_ports                  \
{io_west_in_b[22]}] [get_ports {io_west_in_b[21]}] [get_ports                  \
{io_west_in_b[20]}] [get_ports {io_west_in_b[19]}] [get_ports                  \
{io_west_in_b[18]}] [get_ports {io_west_in_b[17]}] [get_ports                  \
{io_west_in_b[16]}] [get_ports {io_west_in_b[15]}] [get_ports                  \
{io_west_in_b[14]}] [get_ports {io_west_in_b[13]}] [get_ports                  \
{io_west_in_b[12]}] [get_ports {io_west_in_b[11]}] [get_ports                  \
{io_west_in_b[10]}] [get_ports {io_west_in_b[9]}] [get_ports                   \
{io_west_in_b[8]}] [get_ports {io_west_in_b[7]}] [get_ports {io_west_in_b[6]}] \
[get_ports {io_west_in_b[5]}] [get_ports {io_west_in_b[4]}] [get_ports         \
{io_west_in_b[3]}] [get_ports {io_west_in_b[2]}] [get_ports {io_west_in_b[1]}] \
[get_ports {io_west_in_b[0]}] [get_ports {io_south_in_a[63]}] [get_ports       \
{io_south_in_a[62]}] [get_ports {io_south_in_a[61]}] [get_ports                \
{io_south_in_a[60]}] [get_ports {io_south_in_a[59]}] [get_ports                \
{io_south_in_a[58]}] [get_ports {io_south_in_a[57]}] [get_ports                \
{io_south_in_a[56]}] [get_ports {io_south_in_a[55]}] [get_ports                \
{io_south_in_a[54]}] [get_ports {io_south_in_a[53]}] [get_ports                \
{io_south_in_a[52]}] [get_ports {io_south_in_a[51]}] [get_ports                \
{io_south_in_a[50]}] [get_ports {io_south_in_a[49]}] [get_ports                \
{io_south_in_a[48]}] [get_ports {io_south_in_a[47]}] [get_ports                \
{io_south_in_a[46]}] [get_ports {io_south_in_a[45]}] [get_ports                \
{io_south_in_a[44]}] [get_ports {io_south_in_a[43]}] [get_ports                \
{io_south_in_a[42]}] [get_ports {io_south_in_a[41]}] [get_ports                \
{io_south_in_a[40]}] [get_ports {io_south_in_a[39]}] [get_ports                \
{io_south_in_a[38]}] [get_ports {io_south_in_a[37]}] [get_ports                \
{io_south_in_a[36]}] [get_ports {io_south_in_a[35]}] [get_ports                \
{io_south_in_a[34]}] [get_ports {io_south_in_a[33]}] [get_ports                \
{io_south_in_a[32]}] [get_ports {io_south_in_a[31]}] [get_ports                \
{io_south_in_a[30]}] [get_ports {io_south_in_a[29]}] [get_ports                \
{io_south_in_a[28]}] [get_ports {io_south_in_a[27]}] [get_ports                \
{io_south_in_a[26]}] [get_ports {io_south_in_a[25]}] [get_ports                \
{io_south_in_a[24]}] [get_ports {io_south_in_a[23]}] [get_ports                \
{io_south_in_a[22]}] [get_ports {io_south_in_a[21]}] [get_ports                \
{io_south_in_a[20]}] [get_ports {io_south_in_a[19]}] [get_ports                \
{io_south_in_a[18]}] [get_ports {io_south_in_a[17]}] [get_ports                \
{io_south_in_a[16]}] [get_ports {io_south_in_a[15]}] [get_ports                \
{io_south_in_a[14]}] [get_ports {io_south_in_a[13]}] [get_ports                \
{io_south_in_a[12]}] [get_ports {io_south_in_a[11]}] [get_ports                \
{io_south_in_a[10]}] [get_ports {io_south_in_a[9]}] [get_ports                 \
{io_south_in_a[8]}] [get_ports {io_south_in_a[7]}] [get_ports                  \
{io_south_in_a[6]}] [get_ports {io_south_in_a[5]}] [get_ports                  \
{io_south_in_a[4]}] [get_ports {io_south_in_a[3]}] [get_ports                  \
{io_south_in_a[2]}] [get_ports {io_south_in_a[1]}] [get_ports                  \
{io_south_in_a[0]}] [get_ports {io_south_in_b[63]}] [get_ports                 \
{io_south_in_b[62]}] [get_ports {io_south_in_b[61]}] [get_ports                \
{io_south_in_b[60]}] [get_ports {io_south_in_b[59]}] [get_ports                \
{io_south_in_b[58]}] [get_ports {io_south_in_b[57]}] [get_ports                \
{io_south_in_b[56]}] [get_ports {io_south_in_b[55]}] [get_ports                \
{io_south_in_b[54]}] [get_ports {io_south_in_b[53]}] [get_ports                \
{io_south_in_b[52]}] [get_ports {io_south_in_b[51]}] [get_ports                \
{io_south_in_b[50]}] [get_ports {io_south_in_b[49]}] [get_ports                \
{io_south_in_b[48]}] [get_ports {io_south_in_b[47]}] [get_ports                \
{io_south_in_b[46]}] [get_ports {io_south_in_b[45]}] [get_ports                \
{io_south_in_b[44]}] [get_ports {io_south_in_b[43]}] [get_ports                \
{io_south_in_b[42]}] [get_ports {io_south_in_b[41]}] [get_ports                \
{io_south_in_b[40]}] [get_ports {io_south_in_b[39]}] [get_ports                \
{io_south_in_b[38]}] [get_ports {io_south_in_b[37]}] [get_ports                \
{io_south_in_b[36]}] [get_ports {io_south_in_b[35]}] [get_ports                \
{io_south_in_b[34]}] [get_ports {io_south_in_b[33]}] [get_ports                \
{io_south_in_b[32]}] [get_ports {io_south_in_b[31]}] [get_ports                \
{io_south_in_b[30]}] [get_ports {io_south_in_b[29]}] [get_ports                \
{io_south_in_b[28]}] [get_ports {io_south_in_b[27]}] [get_ports                \
{io_south_in_b[26]}] [get_ports {io_south_in_b[25]}] [get_ports                \
{io_south_in_b[24]}] [get_ports {io_south_in_b[23]}] [get_ports                \
{io_south_in_b[22]}] [get_ports {io_south_in_b[21]}] [get_ports                \
{io_south_in_b[20]}] [get_ports {io_south_in_b[19]}] [get_ports                \
{io_south_in_b[18]}] [get_ports {io_south_in_b[17]}] [get_ports                \
{io_south_in_b[16]}] [get_ports {io_south_in_b[15]}] [get_ports                \
{io_south_in_b[14]}] [get_ports {io_south_in_b[13]}] [get_ports                \
{io_south_in_b[12]}] [get_ports {io_south_in_b[11]}] [get_ports                \
{io_south_in_b[10]}] [get_ports {io_south_in_b[9]}] [get_ports                 \
{io_south_in_b[8]}] [get_ports {io_south_in_b[7]}] [get_ports                  \
{io_south_in_b[6]}] [get_ports {io_south_in_b[5]}] [get_ports                  \
{io_south_in_b[4]}] [get_ports {io_south_in_b[3]}] [get_ports                  \
{io_south_in_b[2]}] [get_ports {io_south_in_b[1]}] [get_ports                  \
{io_south_in_b[0]}]]
group_path -name output_group  -to [list [get_ports {io_north_out_a[63]}] [get_ports {io_north_out_a[62]}]   \
[get_ports {io_north_out_a[61]}] [get_ports {io_north_out_a[60]}] [get_ports   \
{io_north_out_a[59]}] [get_ports {io_north_out_a[58]}] [get_ports              \
{io_north_out_a[57]}] [get_ports {io_north_out_a[56]}] [get_ports              \
{io_north_out_a[55]}] [get_ports {io_north_out_a[54]}] [get_ports              \
{io_north_out_a[53]}] [get_ports {io_north_out_a[52]}] [get_ports              \
{io_north_out_a[51]}] [get_ports {io_north_out_a[50]}] [get_ports              \
{io_north_out_a[49]}] [get_ports {io_north_out_a[48]}] [get_ports              \
{io_north_out_a[47]}] [get_ports {io_north_out_a[46]}] [get_ports              \
{io_north_out_a[45]}] [get_ports {io_north_out_a[44]}] [get_ports              \
{io_north_out_a[43]}] [get_ports {io_north_out_a[42]}] [get_ports              \
{io_north_out_a[41]}] [get_ports {io_north_out_a[40]}] [get_ports              \
{io_north_out_a[39]}] [get_ports {io_north_out_a[38]}] [get_ports              \
{io_north_out_a[37]}] [get_ports {io_north_out_a[36]}] [get_ports              \
{io_north_out_a[35]}] [get_ports {io_north_out_a[34]}] [get_ports              \
{io_north_out_a[33]}] [get_ports {io_north_out_a[32]}] [get_ports              \
{io_north_out_a[31]}] [get_ports {io_north_out_a[30]}] [get_ports              \
{io_north_out_a[29]}] [get_ports {io_north_out_a[28]}] [get_ports              \
{io_north_out_a[27]}] [get_ports {io_north_out_a[26]}] [get_ports              \
{io_north_out_a[25]}] [get_ports {io_north_out_a[24]}] [get_ports              \
{io_north_out_a[23]}] [get_ports {io_north_out_a[22]}] [get_ports              \
{io_north_out_a[21]}] [get_ports {io_north_out_a[20]}] [get_ports              \
{io_north_out_a[19]}] [get_ports {io_north_out_a[18]}] [get_ports              \
{io_north_out_a[17]}] [get_ports {io_north_out_a[16]}] [get_ports              \
{io_north_out_a[15]}] [get_ports {io_north_out_a[14]}] [get_ports              \
{io_north_out_a[13]}] [get_ports {io_north_out_a[12]}] [get_ports              \
{io_north_out_a[11]}] [get_ports {io_north_out_a[10]}] [get_ports              \
{io_north_out_a[9]}] [get_ports {io_north_out_a[8]}] [get_ports                \
{io_north_out_a[7]}] [get_ports {io_north_out_a[6]}] [get_ports                \
{io_north_out_a[5]}] [get_ports {io_north_out_a[4]}] [get_ports                \
{io_north_out_a[3]}] [get_ports {io_north_out_a[2]}] [get_ports                \
{io_north_out_a[1]}] [get_ports {io_north_out_a[0]}] [get_ports                \
{io_north_out_b[63]}] [get_ports {io_north_out_b[62]}] [get_ports              \
{io_north_out_b[61]}] [get_ports {io_north_out_b[60]}] [get_ports              \
{io_north_out_b[59]}] [get_ports {io_north_out_b[58]}] [get_ports              \
{io_north_out_b[57]}] [get_ports {io_north_out_b[56]}] [get_ports              \
{io_north_out_b[55]}] [get_ports {io_north_out_b[54]}] [get_ports              \
{io_north_out_b[53]}] [get_ports {io_north_out_b[52]}] [get_ports              \
{io_north_out_b[51]}] [get_ports {io_north_out_b[50]}] [get_ports              \
{io_north_out_b[49]}] [get_ports {io_north_out_b[48]}] [get_ports              \
{io_north_out_b[47]}] [get_ports {io_north_out_b[46]}] [get_ports              \
{io_north_out_b[45]}] [get_ports {io_north_out_b[44]}] [get_ports              \
{io_north_out_b[43]}] [get_ports {io_north_out_b[42]}] [get_ports              \
{io_north_out_b[41]}] [get_ports {io_north_out_b[40]}] [get_ports              \
{io_north_out_b[39]}] [get_ports {io_north_out_b[38]}] [get_ports              \
{io_north_out_b[37]}] [get_ports {io_north_out_b[36]}] [get_ports              \
{io_north_out_b[35]}] [get_ports {io_north_out_b[34]}] [get_ports              \
{io_north_out_b[33]}] [get_ports {io_north_out_b[32]}] [get_ports              \
{io_north_out_b[31]}] [get_ports {io_north_out_b[30]}] [get_ports              \
{io_north_out_b[29]}] [get_ports {io_north_out_b[28]}] [get_ports              \
{io_north_out_b[27]}] [get_ports {io_north_out_b[26]}] [get_ports              \
{io_north_out_b[25]}] [get_ports {io_north_out_b[24]}] [get_ports              \
{io_north_out_b[23]}] [get_ports {io_north_out_b[22]}] [get_ports              \
{io_north_out_b[21]}] [get_ports {io_north_out_b[20]}] [get_ports              \
{io_north_out_b[19]}] [get_ports {io_north_out_b[18]}] [get_ports              \
{io_north_out_b[17]}] [get_ports {io_north_out_b[16]}] [get_ports              \
{io_north_out_b[15]}] [get_ports {io_north_out_b[14]}] [get_ports              \
{io_north_out_b[13]}] [get_ports {io_north_out_b[12]}] [get_ports              \
{io_north_out_b[11]}] [get_ports {io_north_out_b[10]}] [get_ports              \
{io_north_out_b[9]}] [get_ports {io_north_out_b[8]}] [get_ports                \
{io_north_out_b[7]}] [get_ports {io_north_out_b[6]}] [get_ports                \
{io_north_out_b[5]}] [get_ports {io_north_out_b[4]}] [get_ports                \
{io_north_out_b[3]}] [get_ports {io_north_out_b[2]}] [get_ports                \
{io_north_out_b[1]}] [get_ports {io_north_out_b[0]}] [get_ports                \
{io_east_out_a[63]}] [get_ports {io_east_out_a[62]}] [get_ports                \
{io_east_out_a[61]}] [get_ports {io_east_out_a[60]}] [get_ports                \
{io_east_out_a[59]}] [get_ports {io_east_out_a[58]}] [get_ports                \
{io_east_out_a[57]}] [get_ports {io_east_out_a[56]}] [get_ports                \
{io_east_out_a[55]}] [get_ports {io_east_out_a[54]}] [get_ports                \
{io_east_out_a[53]}] [get_ports {io_east_out_a[52]}] [get_ports                \
{io_east_out_a[51]}] [get_ports {io_east_out_a[50]}] [get_ports                \
{io_east_out_a[49]}] [get_ports {io_east_out_a[48]}] [get_ports                \
{io_east_out_a[47]}] [get_ports {io_east_out_a[46]}] [get_ports                \
{io_east_out_a[45]}] [get_ports {io_east_out_a[44]}] [get_ports                \
{io_east_out_a[43]}] [get_ports {io_east_out_a[42]}] [get_ports                \
{io_east_out_a[41]}] [get_ports {io_east_out_a[40]}] [get_ports                \
{io_east_out_a[39]}] [get_ports {io_east_out_a[38]}] [get_ports                \
{io_east_out_a[37]}] [get_ports {io_east_out_a[36]}] [get_ports                \
{io_east_out_a[35]}] [get_ports {io_east_out_a[34]}] [get_ports                \
{io_east_out_a[33]}] [get_ports {io_east_out_a[32]}] [get_ports                \
{io_east_out_a[31]}] [get_ports {io_east_out_a[30]}] [get_ports                \
{io_east_out_a[29]}] [get_ports {io_east_out_a[28]}] [get_ports                \
{io_east_out_a[27]}] [get_ports {io_east_out_a[26]}] [get_ports                \
{io_east_out_a[25]}] [get_ports {io_east_out_a[24]}] [get_ports                \
{io_east_out_a[23]}] [get_ports {io_east_out_a[22]}] [get_ports                \
{io_east_out_a[21]}] [get_ports {io_east_out_a[20]}] [get_ports                \
{io_east_out_a[19]}] [get_ports {io_east_out_a[18]}] [get_ports                \
{io_east_out_a[17]}] [get_ports {io_east_out_a[16]}] [get_ports                \
{io_east_out_a[15]}] [get_ports {io_east_out_a[14]}] [get_ports                \
{io_east_out_a[13]}] [get_ports {io_east_out_a[12]}] [get_ports                \
{io_east_out_a[11]}] [get_ports {io_east_out_a[10]}] [get_ports                \
{io_east_out_a[9]}] [get_ports {io_east_out_a[8]}] [get_ports                  \
{io_east_out_a[7]}] [get_ports {io_east_out_a[6]}] [get_ports                  \
{io_east_out_a[5]}] [get_ports {io_east_out_a[4]}] [get_ports                  \
{io_east_out_a[3]}] [get_ports {io_east_out_a[2]}] [get_ports                  \
{io_east_out_a[1]}] [get_ports {io_east_out_a[0]}] [get_ports                  \
{io_east_out_b[63]}] [get_ports {io_east_out_b[62]}] [get_ports                \
{io_east_out_b[61]}] [get_ports {io_east_out_b[60]}] [get_ports                \
{io_east_out_b[59]}] [get_ports {io_east_out_b[58]}] [get_ports                \
{io_east_out_b[57]}] [get_ports {io_east_out_b[56]}] [get_ports                \
{io_east_out_b[55]}] [get_ports {io_east_out_b[54]}] [get_ports                \
{io_east_out_b[53]}] [get_ports {io_east_out_b[52]}] [get_ports                \
{io_east_out_b[51]}] [get_ports {io_east_out_b[50]}] [get_ports                \
{io_east_out_b[49]}] [get_ports {io_east_out_b[48]}] [get_ports                \
{io_east_out_b[47]}] [get_ports {io_east_out_b[46]}] [get_ports                \
{io_east_out_b[45]}] [get_ports {io_east_out_b[44]}] [get_ports                \
{io_east_out_b[43]}] [get_ports {io_east_out_b[42]}] [get_ports                \
{io_east_out_b[41]}] [get_ports {io_east_out_b[40]}] [get_ports                \
{io_east_out_b[39]}] [get_ports {io_east_out_b[38]}] [get_ports                \
{io_east_out_b[37]}] [get_ports {io_east_out_b[36]}] [get_ports                \
{io_east_out_b[35]}] [get_ports {io_east_out_b[34]}] [get_ports                \
{io_east_out_b[33]}] [get_ports {io_east_out_b[32]}] [get_ports                \
{io_east_out_b[31]}] [get_ports {io_east_out_b[30]}] [get_ports                \
{io_east_out_b[29]}] [get_ports {io_east_out_b[28]}] [get_ports                \
{io_east_out_b[27]}] [get_ports {io_east_out_b[26]}] [get_ports                \
{io_east_out_b[25]}] [get_ports {io_east_out_b[24]}] [get_ports                \
{io_east_out_b[23]}] [get_ports {io_east_out_b[22]}] [get_ports                \
{io_east_out_b[21]}] [get_ports {io_east_out_b[20]}] [get_ports                \
{io_east_out_b[19]}] [get_ports {io_east_out_b[18]}] [get_ports                \
{io_east_out_b[17]}] [get_ports {io_east_out_b[16]}] [get_ports                \
{io_east_out_b[15]}] [get_ports {io_east_out_b[14]}] [get_ports                \
{io_east_out_b[13]}] [get_ports {io_east_out_b[12]}] [get_ports                \
{io_east_out_b[11]}] [get_ports {io_east_out_b[10]}] [get_ports                \
{io_east_out_b[9]}] [get_ports {io_east_out_b[8]}] [get_ports                  \
{io_east_out_b[7]}] [get_ports {io_east_out_b[6]}] [get_ports                  \
{io_east_out_b[5]}] [get_ports {io_east_out_b[4]}] [get_ports                  \
{io_east_out_b[3]}] [get_ports {io_east_out_b[2]}] [get_ports                  \
{io_east_out_b[1]}] [get_ports {io_east_out_b[0]}] [get_ports                  \
{io_west_out_a[63]}] [get_ports {io_west_out_a[62]}] [get_ports                \
{io_west_out_a[61]}] [get_ports {io_west_out_a[60]}] [get_ports                \
{io_west_out_a[59]}] [get_ports {io_west_out_a[58]}] [get_ports                \
{io_west_out_a[57]}] [get_ports {io_west_out_a[56]}] [get_ports                \
{io_west_out_a[55]}] [get_ports {io_west_out_a[54]}] [get_ports                \
{io_west_out_a[53]}] [get_ports {io_west_out_a[52]}] [get_ports                \
{io_west_out_a[51]}] [get_ports {io_west_out_a[50]}] [get_ports                \
{io_west_out_a[49]}] [get_ports {io_west_out_a[48]}] [get_ports                \
{io_west_out_a[47]}] [get_ports {io_west_out_a[46]}] [get_ports                \
{io_west_out_a[45]}] [get_ports {io_west_out_a[44]}] [get_ports                \
{io_west_out_a[43]}] [get_ports {io_west_out_a[42]}] [get_ports                \
{io_west_out_a[41]}] [get_ports {io_west_out_a[40]}] [get_ports                \
{io_west_out_a[39]}] [get_ports {io_west_out_a[38]}] [get_ports                \
{io_west_out_a[37]}] [get_ports {io_west_out_a[36]}] [get_ports                \
{io_west_out_a[35]}] [get_ports {io_west_out_a[34]}] [get_ports                \
{io_west_out_a[33]}] [get_ports {io_west_out_a[32]}] [get_ports                \
{io_west_out_a[31]}] [get_ports {io_west_out_a[30]}] [get_ports                \
{io_west_out_a[29]}] [get_ports {io_west_out_a[28]}] [get_ports                \
{io_west_out_a[27]}] [get_ports {io_west_out_a[26]}] [get_ports                \
{io_west_out_a[25]}] [get_ports {io_west_out_a[24]}] [get_ports                \
{io_west_out_a[23]}] [get_ports {io_west_out_a[22]}] [get_ports                \
{io_west_out_a[21]}] [get_ports {io_west_out_a[20]}] [get_ports                \
{io_west_out_a[19]}] [get_ports {io_west_out_a[18]}] [get_ports                \
{io_west_out_a[17]}] [get_ports {io_west_out_a[16]}] [get_ports                \
{io_west_out_a[15]}] [get_ports {io_west_out_a[14]}] [get_ports                \
{io_west_out_a[13]}] [get_ports {io_west_out_a[12]}] [get_ports                \
{io_west_out_a[11]}] [get_ports {io_west_out_a[10]}] [get_ports                \
{io_west_out_a[9]}] [get_ports {io_west_out_a[8]}] [get_ports                  \
{io_west_out_a[7]}] [get_ports {io_west_out_a[6]}] [get_ports                  \
{io_west_out_a[5]}] [get_ports {io_west_out_a[4]}] [get_ports                  \
{io_west_out_a[3]}] [get_ports {io_west_out_a[2]}] [get_ports                  \
{io_west_out_a[1]}] [get_ports {io_west_out_a[0]}] [get_ports                  \
{io_west_out_b[63]}] [get_ports {io_west_out_b[62]}] [get_ports                \
{io_west_out_b[61]}] [get_ports {io_west_out_b[60]}] [get_ports                \
{io_west_out_b[59]}] [get_ports {io_west_out_b[58]}] [get_ports                \
{io_west_out_b[57]}] [get_ports {io_west_out_b[56]}] [get_ports                \
{io_west_out_b[55]}] [get_ports {io_west_out_b[54]}] [get_ports                \
{io_west_out_b[53]}] [get_ports {io_west_out_b[52]}] [get_ports                \
{io_west_out_b[51]}] [get_ports {io_west_out_b[50]}] [get_ports                \
{io_west_out_b[49]}] [get_ports {io_west_out_b[48]}] [get_ports                \
{io_west_out_b[47]}] [get_ports {io_west_out_b[46]}] [get_ports                \
{io_west_out_b[45]}] [get_ports {io_west_out_b[44]}] [get_ports                \
{io_west_out_b[43]}] [get_ports {io_west_out_b[42]}] [get_ports                \
{io_west_out_b[41]}] [get_ports {io_west_out_b[40]}] [get_ports                \
{io_west_out_b[39]}] [get_ports {io_west_out_b[38]}] [get_ports                \
{io_west_out_b[37]}] [get_ports {io_west_out_b[36]}] [get_ports                \
{io_west_out_b[35]}] [get_ports {io_west_out_b[34]}] [get_ports                \
{io_west_out_b[33]}] [get_ports {io_west_out_b[32]}] [get_ports                \
{io_west_out_b[31]}] [get_ports {io_west_out_b[30]}] [get_ports                \
{io_west_out_b[29]}] [get_ports {io_west_out_b[28]}] [get_ports                \
{io_west_out_b[27]}] [get_ports {io_west_out_b[26]}] [get_ports                \
{io_west_out_b[25]}] [get_ports {io_west_out_b[24]}] [get_ports                \
{io_west_out_b[23]}] [get_ports {io_west_out_b[22]}] [get_ports                \
{io_west_out_b[21]}] [get_ports {io_west_out_b[20]}] [get_ports                \
{io_west_out_b[19]}] [get_ports {io_west_out_b[18]}] [get_ports                \
{io_west_out_b[17]}] [get_ports {io_west_out_b[16]}] [get_ports                \
{io_west_out_b[15]}] [get_ports {io_west_out_b[14]}] [get_ports                \
{io_west_out_b[13]}] [get_ports {io_west_out_b[12]}] [get_ports                \
{io_west_out_b[11]}] [get_ports {io_west_out_b[10]}] [get_ports                \
{io_west_out_b[9]}] [get_ports {io_west_out_b[8]}] [get_ports                  \
{io_west_out_b[7]}] [get_ports {io_west_out_b[6]}] [get_ports                  \
{io_west_out_b[5]}] [get_ports {io_west_out_b[4]}] [get_ports                  \
{io_west_out_b[3]}] [get_ports {io_west_out_b[2]}] [get_ports                  \
{io_west_out_b[1]}] [get_ports {io_west_out_b[0]}] [get_ports                  \
{io_south_out_a[63]}] [get_ports {io_south_out_a[62]}] [get_ports              \
{io_south_out_a[61]}] [get_ports {io_south_out_a[60]}] [get_ports              \
{io_south_out_a[59]}] [get_ports {io_south_out_a[58]}] [get_ports              \
{io_south_out_a[57]}] [get_ports {io_south_out_a[56]}] [get_ports              \
{io_south_out_a[55]}] [get_ports {io_south_out_a[54]}] [get_ports              \
{io_south_out_a[53]}] [get_ports {io_south_out_a[52]}] [get_ports              \
{io_south_out_a[51]}] [get_ports {io_south_out_a[50]}] [get_ports              \
{io_south_out_a[49]}] [get_ports {io_south_out_a[48]}] [get_ports              \
{io_south_out_a[47]}] [get_ports {io_south_out_a[46]}] [get_ports              \
{io_south_out_a[45]}] [get_ports {io_south_out_a[44]}] [get_ports              \
{io_south_out_a[43]}] [get_ports {io_south_out_a[42]}] [get_ports              \
{io_south_out_a[41]}] [get_ports {io_south_out_a[40]}] [get_ports              \
{io_south_out_a[39]}] [get_ports {io_south_out_a[38]}] [get_ports              \
{io_south_out_a[37]}] [get_ports {io_south_out_a[36]}] [get_ports              \
{io_south_out_a[35]}] [get_ports {io_south_out_a[34]}] [get_ports              \
{io_south_out_a[33]}] [get_ports {io_south_out_a[32]}] [get_ports              \
{io_south_out_a[31]}] [get_ports {io_south_out_a[30]}] [get_ports              \
{io_south_out_a[29]}] [get_ports {io_south_out_a[28]}] [get_ports              \
{io_south_out_a[27]}] [get_ports {io_south_out_a[26]}] [get_ports              \
{io_south_out_a[25]}] [get_ports {io_south_out_a[24]}] [get_ports              \
{io_south_out_a[23]}] [get_ports {io_south_out_a[22]}] [get_ports              \
{io_south_out_a[21]}] [get_ports {io_south_out_a[20]}] [get_ports              \
{io_south_out_a[19]}] [get_ports {io_south_out_a[18]}] [get_ports              \
{io_south_out_a[17]}] [get_ports {io_south_out_a[16]}] [get_ports              \
{io_south_out_a[15]}] [get_ports {io_south_out_a[14]}] [get_ports              \
{io_south_out_a[13]}] [get_ports {io_south_out_a[12]}] [get_ports              \
{io_south_out_a[11]}] [get_ports {io_south_out_a[10]}] [get_ports              \
{io_south_out_a[9]}] [get_ports {io_south_out_a[8]}] [get_ports                \
{io_south_out_a[7]}] [get_ports {io_south_out_a[6]}] [get_ports                \
{io_south_out_a[5]}] [get_ports {io_south_out_a[4]}] [get_ports                \
{io_south_out_a[3]}] [get_ports {io_south_out_a[2]}] [get_ports                \
{io_south_out_a[1]}] [get_ports {io_south_out_a[0]}] [get_ports                \
{io_south_out_b[63]}] [get_ports {io_south_out_b[62]}] [get_ports              \
{io_south_out_b[61]}] [get_ports {io_south_out_b[60]}] [get_ports              \
{io_south_out_b[59]}] [get_ports {io_south_out_b[58]}] [get_ports              \
{io_south_out_b[57]}] [get_ports {io_south_out_b[56]}] [get_ports              \
{io_south_out_b[55]}] [get_ports {io_south_out_b[54]}] [get_ports              \
{io_south_out_b[53]}] [get_ports {io_south_out_b[52]}] [get_ports              \
{io_south_out_b[51]}] [get_ports {io_south_out_b[50]}] [get_ports              \
{io_south_out_b[49]}] [get_ports {io_south_out_b[48]}] [get_ports              \
{io_south_out_b[47]}] [get_ports {io_south_out_b[46]}] [get_ports              \
{io_south_out_b[45]}] [get_ports {io_south_out_b[44]}] [get_ports              \
{io_south_out_b[43]}] [get_ports {io_south_out_b[42]}] [get_ports              \
{io_south_out_b[41]}] [get_ports {io_south_out_b[40]}] [get_ports              \
{io_south_out_b[39]}] [get_ports {io_south_out_b[38]}] [get_ports              \
{io_south_out_b[37]}] [get_ports {io_south_out_b[36]}] [get_ports              \
{io_south_out_b[35]}] [get_ports {io_south_out_b[34]}] [get_ports              \
{io_south_out_b[33]}] [get_ports {io_south_out_b[32]}] [get_ports              \
{io_south_out_b[31]}] [get_ports {io_south_out_b[30]}] [get_ports              \
{io_south_out_b[29]}] [get_ports {io_south_out_b[28]}] [get_ports              \
{io_south_out_b[27]}] [get_ports {io_south_out_b[26]}] [get_ports              \
{io_south_out_b[25]}] [get_ports {io_south_out_b[24]}] [get_ports              \
{io_south_out_b[23]}] [get_ports {io_south_out_b[22]}] [get_ports              \
{io_south_out_b[21]}] [get_ports {io_south_out_b[20]}] [get_ports              \
{io_south_out_b[19]}] [get_ports {io_south_out_b[18]}] [get_ports              \
{io_south_out_b[17]}] [get_ports {io_south_out_b[16]}] [get_ports              \
{io_south_out_b[15]}] [get_ports {io_south_out_b[14]}] [get_ports              \
{io_south_out_b[13]}] [get_ports {io_south_out_b[12]}] [get_ports              \
{io_south_out_b[11]}] [get_ports {io_south_out_b[10]}] [get_ports              \
{io_south_out_b[9]}] [get_ports {io_south_out_b[8]}] [get_ports                \
{io_south_out_b[7]}] [get_ports {io_south_out_b[6]}] [get_ports                \
{io_south_out_b[5]}] [get_ports {io_south_out_b[4]}] [get_ports                \
{io_south_out_b[3]}] [get_ports {io_south_out_b[2]}] [get_ports                \
{io_south_out_b[1]}] [get_ports {io_south_out_b[0]}]]
